### ISSUE TITLE
Front Door Origin Host Header Not Set Correctly

### ISSUE THREAD

**Issue by PeterShipstoneAND** [DFE-Digital/terraform-azurerm-container-apps-hosting#189]
Accessing container app via Front Door resulted in HTTP 403.  Found the issue, the Origin host header was not being set correctly, and looking at the TF Module documentation setting cdn_frontdoor_origin_host_header_override to null should default it to the host_name, but this does not appear to be the case: 

>  Manually specify the host header that the CDN sends to the target. Defaults to the recieved host header. Set to null to set it to the host_name (cdn_frontdoor_origin_fqdn_override)

Might be related to the following:
![image](https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/assets/132479391/76a5c15a-1561-44cf-bc29-3b0b0649224d)

Ref: https://learn.microsoft.com/en-us/azure/frontdoor/origin?pivots=front-door-standard-premium#origin-host-header

**Comment by Stretch96** [comment]
If you set it to an empty string, or leave the variable unset, does it then work as expected?

I wonder if it's just the documentation that needs ammending
