### ISSUE TITLE
Azure SQL: Configure public_network_access_enabled

### ISSUE THREAD

**Issue by PeterShipstoneAND** [DFE-Digital/terraform-azurerm-container-apps-hosting#208]
`public_network_access_enabled` setting is currently hard coded to `false`.  Please can this be made configurable for deployments that require it to facilitate database upgrades from GitHub/Azure DevOps pipelines.

![image](https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/assets/132479391/d7652d4b-8daf-4079-91e6-f2a70b75a455)

**Comment by DrizzlyOwl** [comment]
https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/pull/173

**Comment by PeterShipstoneAND** [comment]
thank you for implementing this so the default behaviour can be overridden
